### ISSUE TITLE
能否支持文件请求

### ISSUE THREAD

**Issue by Zhengshuda** [faasjs/faasjs#1724]
默认http请求为application/json
希望能支持application/octet-stream

**Comment by zfben** [comment]
建议的最佳实践是将文件直接上传到云端的对象存储服务中，这样可以避免服务器和容器重启或者网络故障导致的文件无法上传或者上传后丢失。

**Comment by zfben** [comment]
@Zhengshuda 如果是独立部署的模式，可以参考这个 Demo： https://github.com/faasjs/starter/blob/main/examples/download.func.ts
