### ISSUE TITLE
create-faas-app bug

### ISSUE THREAD

**Issue by lucianLY** [faasjs/faasjs#289]
➜  Codes npx create-faas-app --name faasjs --example --noprovider
npx: 1 安装成功，用时 3.947 秒
Cannot find module 'commander'
Require stack:
- /Users/lucian/.npm/_npx/44123/lib/node_modules/create-faas-app/dist/index.js
- /Users/lucian/.npm/_npx/44123/lib/node_modules/create-faas-app/index.js

**Comment by zfben** [comment]
Please use npm v8 or higher version.
