### ISSUE TITLE
Vuepress is refactoring on VitePress, and nextra in the React community looks like a good documentation tool

### ISSUE THREAD

**Issue by Germiniku** [faasjs/faasjs#305]
[example docs](https://swr.vercel.app/zh-CN/docs/getting-started) This is an example of a document using nextra,it is a project of [vercel](https://vercel.com/).

**Comment by zfben** [comment]
Emmmm, It's confusing between vuepress2 and vitepress, I use vuepress2 now, it's based on vite too. I think vitepress isn't much better than vuepress2 currently.

In fact, all documents are written with markdown, I didn't use vue actually.

What features do you need which vitepress only?
