### ISSUE TITLE
Expose Node.js HTTP response stream (res) as property of @faasjs/http plugin

### ISSUE THREAD

**Issue by francisfontoura** [faasjs/faasjs#43]

**Comment by zfben** [comment]
@francisfontoura dose tencentcloud support stream response?

**Comment by francisfontoura** [comment]
> @francisfontoura dose tencentcloud support stream response?

Sorry, I don't know, 'cause I use your project as a standalone FaaS server. Maybe not. But response stream could be exposed only in server mode, even so. What do you think? By the way, faasjs is great as standalone server too. I never liked container based FaaS self-hosted solutions, like IronFunctions or OpenFaaS. So, congrats.

**Comment by zfben** [comment]
sorry, Tencentcloud's cloud function dose not support stream response now, so faasjs can't support it too.
