### ISSUE TITLE
有考虑支持其他厂商sdk的规划吗

### ISSUE THREAD

**Issue by Germiniku** [faasjs/faasjs#439]

**Comment by Germiniku** [comment]
现在腾讯云云函数的免费额度调整了 https://cloud.tencent.com/document/product/583/17299
后续路线会支持其他云厂商吗 如Aliyun、aws......
如果支持 我后面会对接aliyun

**Comment by zfben** [comment]
虽然我目前的主要精力在优化FaasJS在单体应用模式（包括被部署在容器集群中）下的开发体验。
但非常欢迎你接入其它云服务商的sdk，你可以提交阿里云适配器的合并请求，我合并后发布到npm。

**Comment by zfben** [comment]
@Germiniku 如果想接入阿里云，可以再次打开这个 issue。
