### ISSUE TITLE
对于文档的一些直观性建议

### ISSUE THREAD

**Issue by little-buddy** [faasjs/faasjs#979]
个人接触过express的框架，看了faas官方文档后最直观的疑问 :
- 一个函数对应着它的业务处理，那么这个函数是如何暴露给外界与 `url` 对应上
- 假设它是在某个云容器里面执行，能否附上所依赖容器平台的文档链接
- 以及该框架最终部署的流程是什么样的？对于部署的限制状况又是怎样的

最后可以附上 express 开发与 Faasjs 开发最终的目录结构对比，来凸显 faasjs的优势

**Comment by zfben** [comment]
感谢反馈，我会思考一下如何更清晰的表现与其它框架的区别。

**Comment by zfben** [comment]
我优化了一下 starter 的说明，你可以先通过在 Github Codespace 运行 starter 项目直观的感受下 FaasJS 的使用体验：https://github.com/faasjs/starter

**Comment by little-buddy** [comment]
装了一系列的包，然后大概理清楚了
使用的原始http作为网关
然后对标云厂商构建了类似云函数生命周期
以使得faasjs可以支持本地部署以及云函数部署

`挺厉害的，架构还是有一定深度的`👍🏻

**Comment by little-buddy** [comment]
👋🏻
